name: run-tests
on: [push]
jobs:
  ubuntu-20-04-go-1-18:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libcryptsetup12 libcryptsetup-dev
      - run: sudo go test -v ./...
  ubuntu-20-04-go-1-17:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libcryptsetup12 libcryptsetup-dev
      - run: sudo go test -v ./...
  ubuntu-18-04-go-1-16:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libcryptsetup12 libcryptsetup-dev
      - run: sudo go test -v ./...
